name: Angular Build and Test
permissions:
  contents: read
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: "npm"
      - run: npm clean-install
      - run: npx playwright install chromium --with-deps
      - run: npx @angular/cli build
      - run: npx @angular/cli test --no-progress --no-watch
      - name: Upload screenshot test failures
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: vitest-screenshot-attachments
          path: .vitest/attachments
          include-hidden-files: true
          retention-days: 5
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: "npm"
      - run: npm clean-install
      - run: npx prettier --check src
