name: Angular Build and Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
      - run: npm clean-install
      - run: npx @angular/cli build
      - run: npx @angular/cli test --no-progress --no-watch
